import { z } from "https://deno.land/x/zod@v3.16.1/index.ts";

export const Contact = z.object({
  id: z.number(),
  nr: z.string(),
  contact_type_id: z.number(),
  name_1: z.string(),
  name_2: z.string().nullable(),
  salutation_id: z.number().nullable(),
  salutation_form: z.number().nullable(),
  title_id: z.number().nullable(),
  birthday: z.string().nullable(),
  address: z.string().nullable(),
  postcode: z.string().nullable(),
  city: z.string().nullable(),
  country_id: z.number().nullable(),
  mail: z.string().nullable(),
  mail_second: z.string().nullable(),
  phone_fixed: z.string().nullable(),
  phone_fixed_second: z.string().nullable(),
  phone_mobile: z.string().nullable(),
  fax: z.string().nullable(),
  url: z.string().nullable(),
  skype_name: z.string().nullable(),
  remarks: z.string().nullable(),
  language_id: z.number().nullable(),
  contact_group_ids: z.string().nullable(),
  contact_branch_ids: z.string().nullable(),
  user_id: z.number(),
  owner_id: z.number(),
  updated_at: z.string(),
});
